# SONAR

In [71]:
import pandas as pd
df=pd.read_csv('sonar.csv')
df.head()

0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109  \
0  0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337   
1  0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598   
2  0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  0.1098  0.1276  0.0598   
3  0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  0.1209  0.2467  0.3564   
4  0.0286  0.0453  0.0277  0.0174  0.0384  0.0990  0.1201  0.1833  0.2105   

   0.2111  ...  0.0027  0.0065  0.0159  0.0072  0.0167  0.0180  0.0084  \
0  0.2872  ...  0.0084  0.0089  0.0048  0.0094  0.0191  0.0140  0.0049   
1  0.6194  ...  0.0232  0.0166  0.0095  0.0180  0.0244  0.0316  0.0164   
2  0.1264  ...  0.0121  0.0036  0.0150  0.0085  0.0073  0.0050  0.0044   
3  0.4459  ...  0.0031  0.0054  0.0105  0.0110  0.0015  0.0072  0.0048   
4  0.3039  ...  0.0045  0.0014  0.0038  0.0013  0.0089  0.0057  0.0027   

   0.0090  0.0032  R  
0  0.0052  0.0044  R  
1  0.0095  0.0078  R  
2  0.0040  0.0117  R  
3  0.0107  0.0094  R  
4  0.0051  0.0062  R  

[5 rows x 61 columns]

# Description of the dataset

The task is to train a the model to discriminate between sonar signals bounced off a metal cylinder(M) and those bounced off a roughly cylindrical rock (R).

There are 111 signals that are bounced back from a metal cylinder(M) 

97 Signals are bounced off from rock(R)

In [72]:
df.shape

(207, 61)

In [73]:
df.columns

Index(['0.0200', '0.0371', '0.0428', '0.0207', '0.0954', '0.0986', '0.1539',
       '0.1601', '0.3109', '0.2111', '0.1609', '0.1582', '0.2238', '0.0645',
       '0.0660', '0.2273', '0.3100', '0.2999', '0.5078', '0.4797', '0.5783',
       '0.5071', '0.4328', '0.5550', '0.6711', '0.6415', '0.7104', '0.8080',
       '0.6791', '0.3857', '0.1307', '0.2604', '0.5121', '0.7547', '0.8537',
       '0.8507', '0.6692', '0.6097', '0.4943', '0.2744', '0.0510', '0.2834',
       '0.2825', '0.4256', '0.2641', '0.1386', '0.1051', '0.1343', '0.0383',
       '0.0324', '0.0232', '0.0027', '0.0065', '0.0159', '0.0072', '0.0167',
       '0.0180', '0.0084', '0.0090', '0.0032', 'R'],
      dtype='object')

In [74]:
df.isnull().sum()

0.0200    0
0.0371    0
0.0428    0
0.0207    0
0.0954    0
         ..
0.0180    0
0.0084    0
0.0090    0
0.0032    0
R         0
Length: 61, dtype: int64

#### There are no null values in our dataset

# Data Preparation

In [75]:
#renaming the column 'R' for our convenience
df.rename(columns = {'R':'Category'}, inplace = True) 
df

0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109  \
0    0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337   
1    0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598   
2    0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  0.1098  0.1276  0.0598   
3    0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  0.1209  0.2467  0.3564   
4    0.0286  0.0453  0.0277  0.0174  0.0384  0.0990  0.1201  0.1833  0.2105   
..      ...     ...     ...     ...     ...     ...     ...     ...     ...   
202  0.0187  0.0346  0.0168  0.0177  0.0393  0.1630  0.2028  0.1694  0.2328   
203  0.0323  0.0101  0.0298  0.0564  0.0760  0.0958  0.0990  0.1018  0.1030   
204  0.0522  0.0437  0.0180  0.0292  0.0351  0.1171  0.1257  0.1178  0.1258   
205  0.0303  0.0353  0.0490  0.0608  0.0167  0.1354  0.1465  0.1123  0.1945   
206  0.0260  0.0363  0.0136  0.0272  0.0214  0.0338  0.0655  0.1400  0.1843   

     0.2111  ...  0.0027  0.0065  0.0159  0.0072  0.0167  0.0180  0.0084  \
0    0.2872  ...  0.0084  0.0089  0.0048  0.0094  0.0191  0.0140  0.0049   
1    0.6194  ...  0.0232  0.0166  0.0095  0.0180  0.0244  0.0316  0.0164   
2    0.1264  ...  0.0121  0.0036  0.0150  0.0085  0.0073  0.0050  0.0044   
3    0.4459  ...  0.0031  0.0054  0.0105  0.0110  0.0015  0.0072  0.0048   
4    0.3039  ...  0.0045  0.0014  0.0038  0.0013  0.0089  0.0057  0.0027   
..      ...  ...     ...     ...     ...     ...     ...     ...     ...   
202  0.2684  ...  0.0116  0.0098  0.0199  0.0033  0.0101  0.0065  0.0115   
203  0.2154  ...  0.0061  0.0093  0.0135  0.0063  0.0063  0.0034  0.0032   
204  0.2529  ...  0.0160  0.0029  0.0051  0.0062  0.0089  0.0140  0.0138   
205  0.2354  ...  0.0086  0.0046  0.0126  0.0036  0.0035  0.0034  0.0079   
206  0.2354  ...  0.0146  0.0129  0.0047  0.0039  0.0061  0.0040  0.0036   

     0.0090  0.0032  Category  
0    0.0052  0.0044         R  
1    0.0095  0.0078         R  
2    0.0040  0.0117         R  
3    0.0107  0.0094         R  
4    0.0051  0.0062         R  
..      ...     ...       ...  
202  0.0193  0.0157         M  
203  0.0062  0.0067         M  
204  0.0077  0.0031         M  
205  0.0036  0.0048         M  
206  0.0061  0.0115         M  

[207 rows x 61 columns]

#### Setting the inputs and target variable

In [76]:
#inputs
x=df.drop('Category',axis=1)
x.sample()

0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109  \
135  0.1088  0.1278  0.0926  0.1234  0.1276  0.1731  0.1948  0.4262  0.6828   

     0.2111  ...  0.0232  0.0027  0.0065  0.0159  0.0072  0.0167  0.0180  \
135  0.5761  ...   0.014  0.0455  0.0213  0.0082  0.0124  0.0167  0.0103   

     0.0084  0.0090  0.0032  
135  0.0205  0.0178  0.0187  

[1 rows x 60 columns]

In [77]:
#target variable---> 'Category'

y=df['Category']
y.head()

0    R
1    R
2    R
3    R
4    R
Name: Category, dtype: object

we can see that there are too many input columns (61) in the data set.It is a tedious process to make EDA on such large datasets.hence we opt for PCA

# Principle Component Analysis

PCA, is a dimensionality-reduction method that is often used to reduce the dimensionality of large data sets, by transforming a large set of variables into a smaller one that still contains most of the information in the large set.

#### before performing pca lets standardise the values to 0 and 1 using minmax scaler as there are no negative values

In [78]:
#standardizing the values
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
x_scaled = scaler.fit_transform(x)  #the scaled values are saved to x_scaled

In [79]:
#pca
from sklearn.decomposition import PCA
pca=PCA(n_components=10)
x=pca.fit_transform(x_scaled) #passing the 10 scaled columns to x

In [80]:
#reduced dimension of the data set
print(x.shape)
print(y.shape)

(207, 10)
(207,)


#### As there are 2 values in category lets perform logistic regression on the dataset

# Label encoding

In [81]:
#one hot encoder can also be used here
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(y)
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0])

#### 1----> R

0---->M

#### Now all are values are in continuous form so we can proceed with logistic regression

# Logistic Regression

In [82]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import r2_score
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_score


x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=329)
Lg=LogisticRegression()
Lg.fit(x_train,y_train)
y_pred=Lg.predict(x_test)
score=r2_score(y_test,y_pred)
accscore=accuracy_score(y_test,y_pred)
cvscore=cross_val_score(Lg,x_train,y_train,cv=5).mean()

print(f"r2 score is {score*100} and cross validation score is {cvscore*100} and accuracy score is {accscore*100}")

r2 score is 61.81818181818181 and cross validation score is 72.26600985221674 and accuracy score is 90.47619047619048


# Saving the model

In [83]:
import pickle
filename='sonar_model.pkl'
pickle.dump(Lg,open(filename,'wb'))  #saving the trained model 

In [84]:
with open('sonar_model.pkl','rb') as f:
    x=pickle.load(f)

# Comparing the predicted and actual values

In [85]:
#holding actual values in array a
import numpy as np
a=np.array(y_test)
a

array([0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1])

In [86]:
#the predicted values are stored
predicted=np.array(Lg.predict(x_test))
predicted

array([0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1,
       1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1])

In [87]:
df_mod=pd.DataFrame({'actual values':a,'predicted values':predicted})
df_mod

actual values  predicted values
0               0                 0
1               1                 1
2               1                 1
3               0                 0
4               0                 0
..            ...               ...
58              0                 0
59              0                 0
60              1                 1
61              0                 0
62              1                 1

[63 rows x 2 columns]

In [88]:
y_test.shape

(63,)

# conclusion

#### we can see that the model is very well trained and the predicted and actual values are same